[package]
name = "terraformer3d"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
description = "A 3d game engine for quantii"
repository = "https://github.com/SpectralProject/terraformer-3d"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.0"
winit = "0.26"
cgmath = "0.18"
env_logger = "0.9"
log = "0.4"
wgpu = "0.12"
pollster = "0.2"
